import fs from "node:fs";
import vm from "node:vm";
const base = new URL("./", import.meta.url);
const context = { window: {}, structuredClone };
vm.runInNewContext(fs.readFileSync(new URL("../../frontend/public/dark-pattern-demo/scenarios.js", base), "utf8"), context);
const data = context.window.DEMO_SCENARIOS.credit;
const source = fs.readFileSync(new URL("source.js", base), "utf8");
fs.writeFileSync(new URL("code.js", base), `// Generated by node demo/figma/build.mjs\nconst DEMO = ${JSON.stringify(data, null, 2)};\n${source}`);
fs.writeFileSync(new URL("flow.json", base), JSON.stringify(data, null, 2) + "\n");

vm.runInNewContext(fs.readFileSync(new URL("../../frontend/public/dark-pattern-demo/variants.js", base), "utf8"), context);
fs.writeFileSync(new URL("variants.json", base), JSON.stringify(Object.fromEntries(Object.entries(context.window.DEMO_VARIANTS).map(([id, scenarios]) => [id, scenarios.credit])), null, 2) + "\n");
